### PR TITLE
DSP-2097: Rel 16903 merge to master

### PR DESCRIPTION
**Pull request by kaisdewani**

### CODE REVIEW

**Review by dannyc96 — APPROVED** [review]
Update.ps1 is little concerning with how much longer the new signature is versus the older signature. I approve this change knowing QA will test and verify the new signature and we can revert back if needed

**Review by ssmendon — COMMENTED** [review]
Linux scripts look good. `Update.sh` has no changes from `Update.sh.asc`. 

I do think we should use a detached signature in the future. Just think it makes more sense.

```console
❯ gpg --verify Update.sh.asc
gpg: Signature made Thu Feb 16 12:47:22 2023 MST
gpg:                using RSA key 43DA4FE57AF43AF2D40FD377A042B6B30A7F4302
gpg: Good signature from "Acronis SCS <np@acronisscs.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 43DA 4FE5 7AF4 3AF2 D40F  D377 A042 B6B3 0A7F 4302
gpg: WARNING: not a detached signature; file 'Update.sh' was NOT verified!
```

```console
❯ difft Update.sh Update.sh.asc
Update.sh.asc --- 1/2 --- Text
  1 -----BEGIN PGP SIGNED MESSAGE-----
  2 Hash: SHA256
  3 
1 4 #!/bin/sh
2 5 

Update.sh.asc --- 2/2 --- Text
33     fi                                                                                                                  36     fi
34 else                                                                                                                    37 else
35     echo "Installed version is the lastest ${verLatest[0]}.${verLatest[1]}.${verLatest[2]}, no update available"        38     echo "Installed version is the lastest ${verLatest[0]}.${verLatest[1]}.${verLatest[2]}, no update available"
36 fi                                                                                                                      39 fi
                                                                                                                           40 -----BEGIN PGP SIGNATURE-----
                                                                                                                           41 
                                                                                                                           42 iQEzBAEBCAAdFiEEQ9pP5Xr0OvLUD9N3oEK2swp/QwIFAmPuiEoACgkQoEK2swp/
                                                                                                                           43 QwLyXgf/fiSPI/co5zW2PL6j1HXV5uNyngcrsF3SZqsERDojhzW3H4mjfnZjkPy/
                                                                                                                           44 fy3sAQe5aUjBOAy/WCFSHtYlpr0AXF4mDmPa9AKggKKdfoCdaHz/Lkq/0VY2oa9t
                                                                                                                           45 F5jPUfpvDE9PYDjueW2EWfWOqXkimcnQYatu54xpzZWKuQynVa98CcIGv+FMoTkm
                                                                                                                           46 pxdvHixSW1TCQOJlVzw3pJbXMmwy0b1WmrN+7fyqBNxqpidQmLVqvGKUm4a0JDy7
                                                                                                                           47 tME0uMPZoPBAvCxQXdwU6zAo/3OEy+DhQTe6n1XMUaKGHsvrA+Yc4tWAgGygQXJr
                                                                                                                           48 4WBk2zJ3nxLSOQdBrrPYilQG4BSnkQ==
                                                                                                                           49 =+xJP
                                                                                                                           50 -----END PGP SIGNATURE-----
```

**Review by ssmendon — APPROVED** [review]
Windows Authenticode signatures look valid.

```console
❯ Get-AuthenticodeSignature -FilePath .\Update.ps1 | Select-Object -Property SignerCertificate, Status, StatusMessage, SignatureType | Format-List | clip
SignerCertificate : [Subject]
                      CN="ACRONIS SCS, INC.", O="ACRONIS SCS, INC.", L=Scottsdale, S=Arizona, C=US, SERIALNUMBER=6185586, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=Delaware, OID.1.3.6.1.4.1.311.60.2.1.3=US
                    
                    [Issuer]
                      CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1, O="DigiCert, Inc.", C=US
                    
                    [Serial Number]
                      0E4277CF0952E864CEBE3863D5688584
                    
                    [Not Before]
                      5/4/2022 5:00:00 PM
                    
                    [Not After]
                      5/4/2023 4:59:59 PM
                    
                    [Thumbprint]
                      69CA91DC85C948020B3F323ACF1E59059A81ED2F
                    
Status            : Valid
StatusMessage     : Signature verified.
SignatureType     : Authenticode
```

**Comment by bpseward** [comment]
Approved to merge after the release goes live.

**Pull request merged**
